#!/bin/bash
initial_wd="$(PWD)"
session="$(basename "$initial_wd")"
session_wd="$initial_wd"

############################### OPEN DIRS ###############################

tmux has-session -t $session 2>/dev/null
if [[ $? != 0 ]]
then
	tmux new-session -d -n Terminal -s "$session"
	tmux send-keys "cd "$session_wd"" Enter
	tmux send-keys "open_session "$session_wd"" Enter
	tmux split-window -vb -t "$session":0 "vim ./"
fi

tmux attach-session -t $session
